#!/usr/bin/bash

/usr/bin/firewall-cmd --zone=public --add-port=2049/tcp --permanent
/usr/bin/firewall-cmd --zone=public --add-port=2049/udp --permanent
/usr/bin/firewall-cmd --zone=public --add-port=111/tcp --permanent
/usr/bin/firewall-cmd --zone=public --add-port=111/udp --permanent
/usr/bin/firewall-cmd --zone=public --add-port=20048/tcp --permanent
/usr/bin/firewall-cmd --zone=public --add-port=20048/udp --permanent
/usr/bin/firewall-cmd --reload

